google_chat:
  webhook_url: ''
reports:
  formats:
  - html
  - json
  output_dir: reports
scan_policies:
  comprehensive:
    ascan_delay_in_ms: 0
    ascan_policy: Default Policy
    ascan_threads_per_host: 4
    spider_max_children: 10
    spider_max_depth: 10
    spider_max_duration: 30
  default:
    ascan_delay_in_ms: 0
    ascan_policy: Default Policy
    ascan_threads_per_host: 2
    spider_max_children: 5
    spider_max_depth: 5
    spider_max_duration: 10
  quick:
    ascan_delay_in_ms: 0
    ascan_policy: Light
    ascan_threads_per_host: 1
    spider_max_children: 3
    spider_max_depth: 3
    spider_max_duration: 5
scheduler:
  interval_hours: 24
targets:
  # File-based target management configuration
  source_type: "file_based"  # Options: "file_based", "config_based"
  domains_file: "targets/domains.txt"
  subdomains_dir: "targets/subdomains"

  # Default scan policies for different target types
  default_policies:
    main_domain: "default"
    subdomain: "quick"
    new_subdomain: "quick"  # Policy for newly discovered subdomains

  # Target discovery settings
  discovery:
    enabled: true
    auto_scan_new: true  # Automatically scan newly discovered subdomains
    max_targets_per_batch: 50  # For parallel processing

  # Legacy config-based targets (deprecated, use file-based instead)
  # To migrate existing targets, add them to targets/domains.txt
  legacy_targets: []
zap:
  api_key: ''
  host: localhost
  port: 8080
zap_docker:
  api_key: ''
  auto_remove: true
  command: null
  container_name: autodast-zap
  enabled: true
  host_port: 8080
  image: zaproxy/zap-stable
  memory_limit: 2g
  port: 8080
  reports_volume: ./reports
  session_volume: ./zap-session
