# Prometheus Configuration for DAST Monitor

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/rules/*.yml"

scrape_configs:
  # DAST Monitor metrics
  - job_name: 'dast-monitor'
    static_configs:
      - targets: ['dast-monitor:9090']
    scrape_interval: 30s
    metrics_path: /metrics
    
  # Grafana metrics
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: /metrics
    scrape_interval: 30s
    
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

# Alerting configuration (alertmanager not currently deployed)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - alertmanager:9093